### ISSUE TITLE
How does scale work in the config file?

### ISSUE THREAD

**Issue by ch2ohch2oh** [mashephe/AmpTools#22]
It is not clear how the `scale` keyword in the configuration file works. I have a amplitude like this
```
T_tot = a_1 * T_1 + a_2 * T_2
```
where `T`s are my amplitudes and `a`s are the coefficients. It turns out the fitted results depend on the number of events I have, i.e. more events produce larger fitted coefficients. What I want to do is to keep the magnitude of `a`s normalized but I am not sure if this is possible with the `scale` keyword.

**Comment by mashephe** [comment]
Hi,

The scale keyword scales the amplitude (not the intensity).  It is useful for handling things like clebsch gordon coefficients in fits with multiple isospin states.

In addition to scaling by a fixed factor one can scale by a free parameter.

Therefore, if one really wants to normalize magnitude of the fit coefficients then scaling every amplitude by the the square root of the acceptance corrected number of events should do the trick.  (It would be useful to understand the problem a little more to understand whether this this the best guidance.)

Matt


On Jul 22, 2020, at 5:19 PM, dazhi <notifications@github.com<mailto:notifications@github.com>> wrote:



It is not clear how the scale keyword in the configuration file works. I have a amplitude like this

T_tot = a_1 * T_1 + a_2 * T_2


where Ts are my amplitudes and as are the coefficients. It turns out the fitted results depend on the number of events I have, i.e. more events produce larger fitted coefficients. What I want to do is to keep the magnitude of as normalized but I am not sure if this is possible with the scale keyword.

**Comment by ch2ohch2oh** [comment]
This seems to be what I would like to do. Do I have to fit first for the number of efficiency corrected events then manually do the scaling or there is a better way? My config file is like this
```
# 8 spin transitions summed incoherently
sum dalitz s1
...
sum dalitz_s8

# 5 channels for the decay
amplitude dalitz::s1::T1 MyCustomAmplitude1 params...
amplitude dalitz::s1::T2 MyCustomAmplitude2 params...
amplitude dalitz::s1::T3 MyCustomAmplitude3 params...
amplitude dalitz::s1::T4 MyCustomAmplitude4 params...
amplitude dalitz::s1::T5 MyCustomAmplitude5 params...
amplitude dalitz::s2::T1 MyCustomAmplitude1 params...
...
# Assuming initial state unpolarized
consttrain dalitz::s1::T1::dalitz::s2::T1
consttrain dalitz::s1::T1::dalitz::s3::T1
...
# similar lines for s2...s5
```
I tried to scale by adding
```
paramater scaleRatio 1 
scale dalitz::s1::T1 [scaleRatio]
scale dalitz::s1::T2 [scaleRatio]
scale dalitz::s1::T3 [scaleRatio]
...
```
However, this does not work and the `scaleRatio` is just fitted to one. 

Thanks

**Comment by mashephe** [comment]
This approach will leave the fit underconstrained since scaleRatio appears as a product with every amplitude, which is also a free parameter.  If you want to do this, you need to fix one of the amplitudes.

Also note you have misspelled "constrain"

Matt

On Jul 23, 2020, at 2:56 PM, dazhi <notifications@github.com<mailto:notifications@github.com>> wrote:



This seems to be what I would like to do. Do I have to fit first for the number of efficiency corrected events then manually do the scaling or there is a better way? My config file is like this

# 8 spin transitions summed incoherently
sum dalitz s1
...
sum dalitz_s8

# 5 channels for the decay
amplitude dalitz::s1::T1 MyCustomAmplitude1 params...
amplitude dalitz::s1::T2 MyCustomAmplitude2 params...
amplitude dalitz::s1::T3 MyCustomAmplitude3 params...
amplitude dalitz::s1::T4 MyCustomAmplitude4 params...
amplitude dalitz::s1::T5 MyCustomAmplitude5 params...
amplitude dalitz::s2::T1 MyCustomAmplitude1 params...
...
# Assuming initial state unpolarized
consttrain dalitz::s1::T1::dalitz::s2::T1
consttrain dalitz::s1::T1::dalitz::s3::T1
...
# similar lines for s2...s5


I tried to scale by adding

paramater scaleRatio 1
scale dalitz::s1::T1 [scaleRatio]
scale dalitz::s1::T2 [scaleRatio]
scale dalitz::s1::T3 [scaleRatio]
...


However, this does not work and the scaleRatio is just fitted to one.

Thanks

**Comment by ch2ohch2oh** [comment]
Thanks! It worked.
